<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" >

    <xacro:property name="camera_length" value="0.01"/>
    <xacro:property name="camera_width" value="0.1"/>
    <xacro:property name="camera_height" value="0.05"/>
    
    <link name="camera_link">
        <visual>
            <geometry>
                <box size ="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="blue" />
        </visual> 
        <collision>
            <geometry>
                <box size ="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:camera_box_interia m="0.1" l="${camera_length}" w="${camera_width}"
                           h="${camera_height}" xyz= "0 0 0" rpy="0 0 0" /> 
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${(base_length + camera_length) / 2.0} 0 0.1 " rpy="0 0 0" />
    </joint>

    <gazebo reference="camera_link">
        <material>Gazebo/Blue</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose><!--pose is the position and orientation-->   
            <visualize>true</visualize> <!--To visulaize -->     
            <update_rate>10.0</update_rate><!--UPdate rate of gazebo-->
            <!--Plugin is gona situmalate and pub the ros topic -->
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <!--Frame name is basically,where the cam is attached-->
                <frame_name>camera_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>